### ISSUE TITLE
How/Where to get the pre-built OpenVX library binaries

### ISSUE THREAD

**Issue by bhargavthriler** [KhronosGroup/OpenVX-cts#1]
The OpenVX conformance tests README mentions that we need to use the pre-built OpenVX library binaries, for building the OpenVX-CTS. So where can I get the **pre-built OpenVX library binaries**? to use the conformance test suite.

**Comment by kiritigowda** [comment]
@bhargavthriler you can build OpenVX libraries from the OpenVX Sample Implementation or any conformant OpenVX implementation.

https://github.com/KhronosGroup/OpenVX-sample-impl
