### ISSUE TITLE
Fatal error: memory.h: No such file or directory

### ISSUE THREAD

**Issue by igsha** [KhronosGroup/OpenVX-cts#14]
I don't have `memory.h` include file for my embedded platfrom based on clang-4.0.
But the [source](https://github.com/KhronosGroup/OpenVX-cts/blob/openvx_1.3/test_conformance/Networks/src/precisionConverter.c#L3) require it for `memcpy` function (as I thought). But for `memcpy` it is better to use header `string.h` as [standard says](https://en.cppreference.com/w/c/string/byte/memcpy).

**Comment by jessegv** [comment]
Thanks ... I have fixed this in Khronos internal repo, and will sync this to github soon.

**Comment by jessegv** [comment]
Fixed .. closing
