### ISSUE TITLE
Incorrect name in TESTCASE: GraphEnhanced

### ISSUE THREAD

**Issue by kpanfilova** [KhronosGroup/OpenVX-cts#15]
The kernel names do not match the documentation according to the following table.

Link to documentation: [link](https://www.khronos.org/registry/OpenVX/specs/1.3/html/OpenVX_Specification_1_3.html#vxGetKernelByName)

Link to ctcs-test: [link](https://github.com/KhronosGroup/OpenVX-cts/blob/openvx_1.3/test_conformance/test_graph.c#L2915)

|  Kernel name  | string from documentation  | string from cts-tests  | 
| :------------------ | :----------------------------------- | :-------------------------- |
| VX_KERNEL_HOUGH_LINES_P  | "org.khronos.openvx.hough_lines_p" |  "org.khronos.openvx.hough_lines_probabilistic" | 
|  VX_KERNEL_TENSOR_MATRIX_MULTIPLY |  "org.khronos.openvx.tensor_matrix_multiply" | "org.khronos.openvx.tensor_matrix_multiply " |
| VX_KERNEL_COPY | "org.khronos.openvx.copy" | "org.khronos.openvx.copy_node" |
| VX_KERNEL_NON_MAX_SUPPRESSION | "org.khronos.openvx.non_max_suppression" | "org.khronos.openvx.nonmaxsuppression" |
| VX_KERNEL_HOG_FEATURES | "org.khronos.openvx.hog_features" | "org.khronos.openvx.hogfeatures" |
| VX_KERNEL_BILATERAL_FILTER | "org.khronos.openvx.bilateral_filter" | "org.khronos.openvx.bilateral_filter " |
| VX_KERNEL_WEIGHTED_AVERAGE | "org.khronos.openvx.weighted_average" | "org.khronos.openvx.weightedaverage" |

Which names is correct for implementation?

**Comment by jessegv** [comment]
Thanks. you are right.  The sample and cts is not matching the spec.  The spec is correct.  I will update the cts and sample in internal repo and sync to github shortly.

**Comment by jessegv** [comment]
Fixed .. closing
