### ISSUE TITLE
Incorrect status in testvxScheduleGraph

### ISSUE THREAD

**Issue by ashutikhin** [KhronosGroup/OpenVX-cts#16]
In [CTS](https://github.com/KhronosGroup/OpenVX-cts/blob/openvx_1.3/test_conformance/test_graph.c#L2815) it is expected `VX_SUCCESS` after `vxScheduleGraph`. But this function should call `vxVerifyGraph` according to the [documentation](https://www.khronos.org/registry/OpenVX/specs/1.3/html/OpenVX_Specification_1_3.html#_vxschedulegraph).

> If the graph has not been verified, then the implementation verifies the graph immediately [REQ-0633]. If verification fails this function returns a status identical to what vxVerifyGraph would return [REQ-0634].

Because the graph is empty, result of `vxScheduleGraph` should be `VX_ERROR_INVALID_GRAPH`, like [here](https://github.com/KhronosGroup/OpenVX-cts/blob/openvx_1.3/test_conformance/test_graph.c#L2799)?

**Comment by jessegv** [comment]
You are right.  Thanks for reporting this.  I have fixed in Khronos internal repo and will be syncing to github shortly.

**Comment by jessegv** [comment]
fixed .. closing
